WebCaso1/Entities/EstudianteEntidad.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebCaso1.Entities
{
    public class EstudianteEntidad
    {
        public string Nombre { get; set; }

        public DateTime Fecha { get; set; }

        public Decimal Monto { get; set; }
        
        public int TipoCurso { get; set; }

    }

    public class TipoCursoEntidad
    { 
    
        public string DescripcionTipoCurso { get; set; }

    }


}

WebCaso1/Models/EstudianteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebCaso1.Entities;

namespace WebCaso1.Models
{

    public class EstudianteModel
    {
        public void RegistroMatricula(EstudianteEntidad entidad)
        {
            throw new NotImplementedException();
        }
    }
}

WebCaso1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebCaso1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebCaso1/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCaso1.Entities;
using WebCaso1.Models;

namespace WebCaso1.Controllers
{
    public class RegistroController : Controller
    {
        EstudianteModel estudianteModel = new EstudianteModel();


        [HttpGet]
        public ActionResult RegistroMatricula()
        {
            return View();
        }

        [HttpPost]
        [ActionName("RegistroMatricula")]
        public ActionResult RegistroMatriculaPost(EstudianteEntidad entidad)
        {
            estudianteModel.RegistroMatricula(entidad);
            return View("RegistroMatricula");
        }

    }
}

WebCaso1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <div class="row">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Bienvenido! Presiona el cuadro para las opciones</a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("RegistroMatricula", "Registro")">Registro Matrícula</a></li>
            </ul>
        </div>

</main>

WebCaso1/Views/Registro/RegistroMatricula.cshtml
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Formulario de Registro de Matrículas</h4>
            <p class="card-description">
                Complete los siguientes campos para registrar una nueva matrícula.
            </p>
            <form class="forms-sample">

                <div class="form-group row">
                    <label for="studentName" class="col-sm-3 col-form-label">Nombre</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="studentName" placeholder="Nombre del estudiante" required>
                    </div>
                </div>

                <input type="hidden" id="registrationDate">

                <div class="form-group row">
                    <label for="amountPaid" class="col-sm-3 col-form-label">Monto</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="amountPaid" placeholder="Monto pagado" required>
                    </div>
                </div>
                <!-- Campo de Tipo de Curso -->
                <div class="form-group row">
                    <label for="courseType" class="col-sm-3 col-form-label">Tipo de Curso</label>
                    <div class="col-sm-9">
                        <select class="form-control" id="courseType" required>
                            <option value="">Seleccione un tipo de curso</option>
                            <option value="1">En Laboratorio</option>
                            <option value="2">En Clase</option>
                        </select>
                        <small class="text-warning">No se puede matricular más de 3 estudiantes por cada tipo de curso.</small>
                    </div>
                </div>

                <!-- Botones -->
                <button type="submit" class="btn btn-primary mr-2">Registrar</button>
                <button type="reset" class="btn btn-light">Cancelar</button>
            </form>
        </div>
    </div>
</div>

WebCaso1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Skydash Admin</title>

    <link rel="stylesheet" href="~/template/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/template/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/template/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/template/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/template/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/template/js/select.dataTables.min.css">
    <link rel="stylesheet" href="~/template/css/vertical-layout-light/style.css">
</head>
<body>
    <div class="container-scroller">

        @*HEADER*@
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo mr-5" href="@Url.Action("Index","Login")"><img src="~/template/images/logo.svg" class="mr-2" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="@Url.Action("Index","Login")"><img src="~/template/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
                <ul class="navbar-nav mr-lg-2">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                                <span class="input-group-text" id="search">
                                    <i class="icon-search"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">

                    <li class="nav-item nav-profile dropdown">

                        @if (Session["NombreUsuario"] != null)
                        {
                            @Session["NombreUsuario"]
                        }

                        &nbsp;&nbsp;&nbsp;

                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            <img src="~/template/images/faces/face28.jpg" alt="profile" />
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">

                            @if (Session["NombreUsuario"] != null)
                            {
                                <a class="dropdown-item" href="@Url.Action("PerfilUsuario","Usuario")">
                                    <i class="ti-settings text-primary"></i>
                                    Perfil
                                </a>

                                <a class="dropdown-item" href="@Url.Action("CerrarSesion","Login")">
                                    <i class="ti-power-off text-primary"></i>
                                    Cerrar Sesión
                                </a>
                            }
                            else
                            {
                                <a class="dropdown-item" href="@Url.Action("IniciarSesion","Login")">
                                    <i class="ti-home text-primary"></i>
                                    Iniciar Sesión
                                </a>
                            }

                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
            </div>
        </nav>

        <div class="container-fluid page-body-wrapper">
            @*MENU LATERAL*@
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">
                            <i class="icon-grid menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <i class="icon-layout menu-icon"></i>
                            <span class="menu-title">UI Elements</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">

                                <li class="nav-item">
                                    <a href="@Url.Action("ConsultaUsuarios","Usuario")" class=" nav-link">Usuarios</a>
                                </li>


                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>

            <div class="main-panel">
                @*PANEL PRINCIPAL*@
                <div class="content-wrapper">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>

                @*FOOTER*@
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © @DateTime.Now.Year. Derechos Reservados.</span>
                    </div>
                </footer>
            </div>
        </div>
    </div>

    <script src="~/template/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/template/vendors/chart.js/Chart.min.js"></script>
    <script src="~/template/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/template/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <script src="~/template/js/dataTables.select.min.js"></script>
    <script src="~/template/js/off-canvas.js"></script>
    <script src="~/template/js/hoverable-collapse.js"></script>
    <script src="~/template/js/template.js"></script>
    <script src="~/template/js/settings.js"></script>
    <script src="~/template/js/todolist.js"></script>
    <script src="~/template/js/dashboard.js"></script>
    <script src="~/template/js/Chart.roundedBarCharts.js"></script>
</body>
</html>